apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: graphql-gateway
    app.kubernetes.io/name: graphql-gateway
    app.kubernetes.io/version: 1.0.0
  name: graphql-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: graphql-gateway
      app.kubernetes.io/name: graphql-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: graphql-gateway
        app.kubernetes.io/name: graphql-gateway
    spec:
      containers:
        - name: graphql-gateway
          image: ghcr.io/datum-cloud/graphql-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: https
              protocol: TCP
          env:
            - name: LOGGING
              value: info
            - name: KUBECONFIG
              value: /etc/milo-control-plane/config/kubeconfig
            - name: OTLP_URL
              value: opentelemetry-collector-collector.open-telemetry-system.svc.cluster.local:4317
            - name: CERT_DIR
              value: /etc/graphql-gateway/serving-certs
          volumeMounts:
            - name: milo-control-plane-kubeconfig
              mountPath: /etc/milo-control-plane/config
              readOnly: true
            - name: milo-control-plane-certs
              mountPath: /etc/kubernetes/pki/client
              readOnly: true
            - name: trust-bundle
              mountPath: /etc/kubernetes/pki/trust
              readOnly: true
            - name: graphql-gateway-certs
              mountPath: /etc/graphql-gateway/serving-certs
              readOnly: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              path: /healthcheck
              port: 4000
              scheme: HTTPS
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              path: /readiness
              port: 4000
              scheme: HTTPS
      volumes:
        - name: milo-control-plane-kubeconfig
          configMap:
            name: milo-control-plane-kubeconfig
            items:
              - key: kubeconfig
                path: kubeconfig
        - name: milo-control-plane-certs
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: datum-control-plane
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/common-name: graphql-gateway
              csi.cert-manager.io/fs-group: '65534'
              csi.cert-manager.io/key-usages: client auth
        - name: trust-bundle
          configMap:
            name: datum-control-plane-trust-bundle
            items:
              - key: ca.crt
                path: ca.crt
        - name: graphql-gateway-certs
          csi:
            driver: csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              csi.cert-manager.io/issuer-name: datum-control-plane
              csi.cert-manager.io/issuer-kind: ClusterIssuer
              csi.cert-manager.io/common-name: graphql-gateway
              csi.cert-manager.io/dns-names: graphql-gateway,graphql-gateway.graphql-gateway.svc,graphql-gateway.graphql-gateway.svc.cluster.local
              csi.cert-manager.io/fs-group: '65532'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
