apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: graphql-gateway
    app.kubernetes.io/name: graphql-gateway
    app.kubernetes.io/version: 1.0.0
  name: graphql-gateway
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: graphql-gateway
      app.kubernetes.io/name: graphql-gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: graphql-gateway
        app.kubernetes.io/name: graphql-gateway
    spec:
      containers:
        - name: graphql-gateway
          image: ghcr.io/datum-cloud/graphql-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          env:
            - name: LOGGING
              value: debug
            - name: DATUM_BASE_URL
              value: https://milo-apiserver.datum-system.svc.cluster.local:6443
          envFrom:
            - secretRef:
                # Must contain the DATUM_TOKEN environment variable
                name: graphql-gateway
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              path: /healthcheck
              port: 4000
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 10
            httpGet:
              path: /readiness
              port: 4000
              scheme: HTTP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30