apiVersion: v1
kind: ConfigMap
metadata:
  name: milo-control-plane-kubeconfig
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /etc/kubernetes/pki/trust/ca.crt
        server: https://milo-apiserver.datum-system.svc.cluster.local:6443
      name: milo-apiserver
    contexts:
    - context:
        cluster: milo-apiserver
        user: graphql-gateway
      name: graphql-gateway
    current-context: graphql-gateway
    kind: Config
    preferences: {}
    users:
    - name: graphql-gateway
      user:
        client-certificate: /etc/kubernetes/pki/client/tls.crt
        client-key: /etc/kubernetes/pki/client/tls.key
