apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: graphql-gateway
    app.kubernetes.io/name: graphql-gateway
    app.kubernetes.io/version: 1.0.0
  name: graphql-gateway
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: https
      port: 4000
      protocol: TCP
      appProtocol: https
      targetPort: https
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: graphql-gateway
    app.kubernetes.io/name: graphql-gateway
  sessionAffinity: None
  type: ClusterIP
