apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: graphql-gateway
  labels:
    app.kubernetes.io/name: graphql-gateway
    app.kubernetes.io/instance: graphql-gateway
    app.kubernetes.io/component: backend
    monitoring: 'true'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graphql-gateway
      app.kubernetes.io/instance: graphql-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
      relabelings:
        # Add pod name label
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        # Add node name label
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        # Add namespace label
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        # Add service name label
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
  namespaceSelector:
    matchNames:
      - graphql-gateway
