apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # ServiceMonitors for metrics collection
  - servicemonitors/graphqlgateway-servicemonitor.yaml

  # Grafana dashboards
  - dashboards/
